### PR TITLE
getLanguages() returning what is expected

### PR DESCRIPTION
**Pull request by janowsiany**
Add locale to available translations only if translation is not an empty JSON.

### CODE REVIEW

**Comment by janowsiany** [comment]
I am rather thinking about other solution now because this one is not complete. It is not adding locale to available languages, however calling `i18n.isLoaded(locale)` returns true.

**Comment by cristo-rabani** [comment]
Hello,
Everything looks good but for some reason
I have mixed feelings about this pull request.

So, I think we need to talk before this code will be added.

**Comment by radekmie** [comment]
I've just seen the latest version - I'm strongly against another round trip just for this check - previous version was better IMHO.

**Comment by janowsiany** [comment]
Previous solution fixed the issue with with languages list which showed only available ones but it made another issue sucha as: 
```js
i18n.setLocale('en-GB') // en-GB translation does not exists
i18n.getLanguages().includes('en-GB') // which is correct
i18n.isLoaded('en-GB') // true which IMO is not desirable behaviour
```

**Comment by radekmie** [comment]
For me it's 100% OK and desirable - it *is* loaded. Yeah, it's empty, but already loaded. Otherwise, one can load it again and again, because it's not loaded.

**Comment by janowsiany** [comment]
So as @radekmie suggested i reverted my second solution and improved the first one.
@cristo-rabani can i merge this in?

**Pull request merged**
